application: oxfloodwatch
runtime: python27
version: 1
api_version: 1
threadsafe: yes

handlers:

- url: /(.*\.css)
  mime_type: text/css
  static_files: static/\1
  upload: static/(.*\.css)
  secure: always

- url: /(.*\.html)
  mime_type: text/html
  static_files: static/\1
  upload: static/(.*\.html)
  secure: always

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: static/\1
  upload: static/(.*\.js)
  secure: always

- url: /(.*\.txt)
  mime_type: text/plain
  static_files: static/\1
  upload: static/(.*\.txt)

- url: /(.*\.json)
  mime_type: application/json
  static_files: static/\1
  upload: static/(.*\.json)

- url: /(.*\.xml)
  mime_type: text/xml
  static_files: static/\1
  upload: static/(.*\.xml)

- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: static/\1
  upload: static/(.*\.(bmp|gif|ico|jpeg|jpg|png))

- url: /(.*\.(woff|woff2|ttf|svg|eot))
  static_files: static/\1
  upload: static/(.*\.(woff|woff2|ttf|svg|eot))

- url: /api(.*)
  script: main.app
  secure: always

- url: /admin(.*)
  script: main.app
  secure: always
  login: admin

- url: /app.manifest
  mime_type: application/json
  static_files: static/app.manifest
  upload: static/app.manifest
  secure: always

- url: /
  static_files: static/index.html
  upload: static/index.html
  secure: always

- url: /chacks
  static_files: static/index.html
  upload: static/index.html
  secure: always

- url: /sites/(.*)
  static_files: static/index.html
  upload: static/index.html
  secure: always

- url: /pages/(.*)
  static_files: static/index.html
  upload: static/index.html
  secure: always

- url: /manifest\.(.*)
  static_files: static/manifest.\1
  upload: static/manifest.(.*)

- url: /favicon\.(.*)
  static_files: static/favicon.\1
  upload: static/favicon\.(.*)

