application: oxfloodwatch
runtime: python27
version: 1
api_version: 1
threadsafe: yes

handlers:

- url: /(.*\.css)
  mime_type: text/css
  static_files: static/\1
  upload: static/(.*\.css)
  secure: always

- url: /(.*\.html)
  mime_type: text/html
  static_files: static/\1
  upload: static/(.*\.html)
  secure: always

- url: /(.*\.js)
  mime_type: text/javascript
  static_files: static/\1
  upload: static/(.*\.js)
  secure: always

- url: /(.*\.txt)
  mime_type: text/plain
  static_files: static/\1
  upload: static/(.*\.txt)

- url: /(.*\.xml)
  mime_type: application/xml
  static_files: static/\1
  upload: static/(.*\.xml)

# image files
- url: /(.*\.(bmp|gif|ico|jpeg|jpg|png))
  static_files: static/\1
  upload: static/(.*\.(bmp|gif|ico|jpeg|jpg|png))

# font files
- url: /(.*\.(woff|woff2|ttf|svg|eot))
  static_files: static/\1
  upload: static/(.*\.(woff|woff2|ttf|svg|eot))

- url: /(.*.js.map)
  static_files: static/\1
  mime_type: application/json
  upload: static/(.*)
  secure: always

- url: /
  static_files: static/index.html
  upload: static/index.html
  secure: always

- url: /(.*)
  static_files: static/\1
  upload: static/(.*)
  secure: always
